version: '3'

services:
    rabbitmq3:
        image: rabbitmq-cluster-base
        hostname: rabbitmq3
        environment:
            - RABBITMQ_ERLANG_COOKIE=12345
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
        volumes:
            - rabbitmq-03-data:/var/lib/rabbitmq
        ports:
            - "1939:1936"
            - "15675:15672"
            - "5675:5672"
        restart: always

    rabbitmq4:
        image: rabbitmq-cluster-base
        hostname: rabbitmq4
        environment:
            - RABBITMQ_ERLANG_COOKIE=12345
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
        volumes:
            - rabbitmq-04-data:/var/lib/rabbitmq
        ports:
            - "1940:1936"
            - "15676:15672"
            - "5676:5672"
        restart: always

networks:
  default:
    external: true
    name: my-attachable-overlay
        
volumes:
    rabbitmq-03-data:
    rabbitmq-04-data:
