version: '3'

services:
    rabbitmq2:
        image: rabbitmq-cluster-base
        hostname: rabbitmq2
        environment:
            - RABBITMQ_ERLANG_COOKIE=12345
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
        volumes:
            - rabbitmq-02-data:/var/lib/rabbitmq
        ports:
            - "1938:1936"
            - "15674:15672"
            - "5674:5672"
        restart: always

networks:
  default:
    external: true
    name: my-attachable-overlay
  
volumes:
    rabbitmq-02-data:


